DROP TABLE TASK;
CREATE TABLE TASK
(
TASK_ID INT NOT NULL ,
TITLE VARCHAR(100),
DESCRIPTION VARCHAR(500),
DURATION INT,
START_DT TIMESTAMP,
END_DT TIMESTAMP,
OWNER VARCHAR(100),
PRIMARY KEY(TASK_ID)
);